package com.tweetApp.tweetApp.model;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.tweetApp.tweetApp.convertor.ReplyConvertor;

@DynamoDBTable(tableName = "tweets")
@Data
@Component
@Builder
public class Tweet {
	
	@DynamoDBHashKey(attributeName="tweetId")
	private String id;
	
	@DynamoDBAttribute
	private String userName;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private String tweetDes;
	
	@DynamoDBAttribute
	private String tweetTag;
	
	@DynamoDBAttribute
	private String tweetDate;
	
	@DynamoDBAttribute
	private String recActive;
	
	@DynamoDBAttribute(attributeName = "replyList")
    @DynamoDBTypeConverted(converter = ReplyConvertor.class)
	private List<Reply> replyList;
	
	@DynamoDBAttribute
	private int like;

	public Tweet() {
		super();
	}
	
	public Tweet(String id, String userName, String email, String tweetDes, String tweetTag, String tweetDate,
			String recActive, List<Reply> replyList,int like) {
		super();
		this.id = id;
		this.userName = userName;
		this.email = email;
		this.tweetDes = tweetDes;
		this.tweetTag = tweetTag;
		this.tweetDate = tweetDate;
		this.recActive = recActive;
		this.replyList = replyList;
		this.like = like;
	}



	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTweetDes() {
		return tweetDes;
	}

	public void setTweetDes(String tweetDes) {
		this.tweetDes = tweetDes;
	}

	public String getTweetTag() {
		return tweetTag;
	}

	public void setTweetTag(String tweetTag) {
		this.tweetTag = tweetTag;
	}

	public String getTweetDate() {
		return tweetDate;
	}

	public void setTweetDate(String tweetDate) {
		this.tweetDate = tweetDate;
	}

	public String getRecActive() {
		return recActive;
	}

	public void setRecActive(String recActive) {
		this.recActive = recActive;
	}

	public List<Reply> getReplyList() {
		return replyList;
	}

	public void setReplyList(List<Reply> replyList) {
		this.replyList = replyList;
	}

	public int getLike() {
		return like;
	}

	public void setLike(int like) {
		this.like = like;
	}
	
	
}
